### ISSUE TITLE
Update Maven central

### ISSUE THREAD

**Issue by loloMui** [linkedin/rest.li#150]
Hello,
I was wondering if by any chance somebody can publish the latest version of Rest.li (27.3.8) to maven central repository?

Thank you!

**Comment by loloMui** [comment]
Also, how complex/time-consuming it will be to upgrade rest.li to Gradle 5.x?

**Comment by evanw555** [comment]
I'll try to get a new one out to Maven soon.

**Comment by evanw555** [comment]
As for the Gradle upgrade, we've considered that and it looks like it would be pretty time-consuming. We'll revisit that initiative later once it becomes higher priority.

**Comment by loloMui** [comment]
Thank you! looking forward to the new version (27.x) on maven

**Comment by evanw555** [comment]
@loloMui Apologies for the delay. The last release of 27.x (27.7.18) was just released on Maven Central today.
