### ISSUE TITLE
Return sorted set from buildWatchedRestModelInputDirs

### ISSUE THREAD

**Issue by DPUkyle** [linkedin/rest.li#151]
https://github.com/linkedin/rest.li/blob/10b38e03d93525ac201ce911111e825c33cbcc7b/gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/PegasusPlugin.java#L1878

... should return `.collect(Collectors.toCollection(TreeSet::new));`

This is a workaround for gradle/gradle#10987.

It's not really a bug in rest.li, however, it's generally best-practice to use sorted data structures for task inputs/outputs.

**Comment by evanw555** [comment]
Interesting... Is this causing problems for you? Or is this just a general recommendation?

**Comment by DPUkyle** [comment]
It's a workaround for an unrelated bug in Gradle. However, for Gradle caching and performance reasons, tasks and CLIs should always return results in some kind of sorted or reproducible order.

**Comment by evanw555** [comment]
As we discovered, this was already fixed but the code here wasn't up to date, so I'm gonna close this issue. Thanks for pointing this out, though.
