### ISSUE TITLE
Broken link to "Pegasus Data Schema"  in the start/step_by_step page

### ISSUE THREAD

**Issue by jianwu** [linkedin/rest.li#163]
In the document page: 

https://linkedin.github.io/rest.li/start/step_by_step

The link to "Pegasus Data Schema" is broken with 404.

**Comment by nickibi** [comment]
Thanks for reporting the issue, we will fix it shortly.

**Comment by nickibi** [comment]
We fixed the issue, could please check the link again. Thanks.

**Comment by jianwu** [comment]
Good now. Thanks
