### ISSUE TITLE
Parsing of PDL file fails when "record" is part of the namespace or the package

### ISSUE THREAD

**Issue by ischoch** [linkedin/rest.li#194]
Have a simple .pdl schema like this:

```
namespace com.linkedin.k2conflation
package com.linkedin.k2conflation.unusedJavaClasses


record DummyStorageEvent {
  @key
  id: long

  partitioningKey: string

  strValue: string

  active: boolean

  intArrayValue: array[int]
}
```

When I change the namespace or package to include "record" in the name, then I get a parse error:

For instance:
`package com.linkedin.k2conflation.record`

> ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.7ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.7Exception in thread "main" java.io.IOException: /Users/ischoch/k2-conflation_trunk/k2-conflation-test-models/src/main/pegasus/com/linkedin/k2conflation/DummyStorageEvent.pdl,2,52: missing ID at 'record'
> 4,0: extraneous input 'record' expecting ID
> 
>         at com.linkedin.pegasus.generator.FileFormatDataSchemaParser.parseSources(FileFormatDataSchemaParser.java:124)
>         at com.linkedin.pegasus.generator.DataSchemaParser.parseSources(DataSchemaParser.java:153)
>         at com.linkedin.graphql.SchemaGenerator.main(SchemaGenerator.java:83)

Also, if record is even part of the package name or the namespace, then there is a parser error like this:

package name:
`package com.linkedin.k2conflation.unusedJavaClasses.record.x
`

error message:

> ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.7ANTLR Tool version 4.5 used for code generation does not match the current runtime version 4.7ANTLR Runtime version 4.5 used for parser compilation does not match the current runtime version 4.7Exception in thread "main" java.io.IOException: /Users/ischoch/k2-conflation_trunk/k2-conflation-test-models/src/main/pegasus/com/linkedin/k2conflation/DummyStorageEvent.pdl,".x" is an invalid name.
> 2,52: Top level type declaration may not be qualified with a namespace different than the file namespace: record.xrecordDummyStorageEvent{@keyid:longpartitioningKey:stringstrValue:stringactive:booleanintArrayValue:array[int]}
> 
>         at com.linkedin.pegasus.generator.FileFormatDataSchemaParser.parseSources(FileFormatDataSchemaParser.java:124)
>         at com.linkedin.pegasus.generator.DataSchemaParser.parseSources(DataSchemaParser.java:153)
>         at com.linkedin.graphql.SchemaGenerator.main(SchemaGenerator.java:83)

Gradle settings:
"type": "gradle",
    "versions": {
      "java": "1.8.0_121",
      "scala": "2.11.8"
    }

pegasus generator version is 28.1.18

**Comment by evanw555** [comment]
This is expected. `record` is a reserved keyword in the PDL grammar, so it must be escaped with backticks (`` ` ``) when used in names/FQNs

Thus, your examples should be as such:

```
package com.linkedin.k2conflation.`record`
package com.linkedin.k2conflation.unusedJavaClasses.`record`.x
```

See more here: https://linkedin.github.io/rest.li/pdl_syntax#escaping
