### ISSUE TITLE
The latest rest.li artifacts are not present on Maven Central

### ISSUE THREAD

**Issue by ahmedahamid** [linkedin/rest.li#231]
[Brooklin](https://github.com/linkedin/brooklin/) is an open-source LinkedIn project that [depends on rest.li](https://github.com/linkedin/brooklin/blob/master/gradle/dependency-versions.gradle#L17). We recently attempted to upgrade to version `28.1.33` but could not find the latest artifacts on Maven Central. Could you please publish them?

Thanks in advance.

**Comment by evanw555** [comment]
We're currently working on a new solution for uploading public Rest.li artifacts. We should be able to get new artifacts out by the end of this week, but they'll be hosted on Bintray in LinkedIn's repo (`https://bintray.com/linkedin/maven`). We will likely end up syncing it to Maven central, but I'm not sure when that will happen.

**Comment by evanw555** [comment]
@ahmedahamid Update: We got the Bintray uploads configured, and we currently have `28.1.35` uploaded. You can see more here: https://bintray.com/beta/#/linkedin/maven/pegasus?tab=overview

You'll have to add LinkedIn's Bintray Maven repo to your buildscripts like so:

```
repositories {
  maven {
    url "https://dl.bintray.com/linkedin/maven"
  }
}
```

**Comment by ahmedahamid** [comment]
Thanks a lot, @evanw555
