### ISSUE TITLE
Compatibility with Swagger?

### ISSUE THREAD

**Issue by earth2marsh** [linkedin/rest.li#26]
Both rest.li and Swagger are approaching their first major revisions (see yesterday's working group announcement: http://swagger.wordnik.com ).

There will never be as good an opportunity to bring the two description formats closer together.

Is there any chance of this happening? If so, how can we start that conversation?

**Comment by ramtej** [comment]
+1

**Comment by fehguy** [comment]
swagger-codegen 2.0 has a very extensible model for parsing via Java SPI.  So producing a reader for rest.li should be really easy.

**Comment by fab-mindflow** [comment]
Any OpenAPI / Swagger specifications for LinkedIn APIs? Or a converter? 🙏🏻
