### ISSUE TITLE
What are the "Fruits" mentioned in the documentation?

### ISSUE THREAD

**Issue by zackthehuman** [linkedin/rest.li#351]
On the Rest.li Multi-language Compatibility Matrix page under the subheading [Supported Data Templates in Test Suite Spec](https://linkedin.github.io/rest.li/multi_language_compatibility_matrix#supported-data-templates-in-test-suite-spec) it lists "Fruits" in the "Template" column.

I can't find any other documentation about what "Fruits" is besides [examples of enums](https://linkedin.github.io/rest.li/pdl_migration#pdl-is-more-java-like). Is this a documentation error?

**Comment by junchuanwang** [comment]
You are totally right sir, this is wrong.

**Comment by junchuanwang** [comment]
the wiki has been updated
