### ISSUE TITLE
Pegasus gradle plugin not compatible with gradle 6

### ISSUE THREAD

**Issue by mars-lan** [linkedin/rest.li#354]
When applying `pegasus` plugin to a gradle 6 project, it results in the follow error

```
Execution failed for task ':metadata-events:mxe-schemas:changedFilesReport'.
> You must declare outputs or use `TaskOutputs.upToDateWhen()` when using the incremental task API
```

**Comment by evanw555** [comment]
Thanks for bringing this up, we're taking it into consideration and putting it into our backlog. Please let us know the urgency of this for your team/project so that we can prioritize it appropriately.

**Comment by mars-lan** [comment]
Not super urgent. Nothing's dependent on 6.x so far.
