### ISSUE TITLE
"gradle idea" fails

### ISSUE THREAD

**Issue by kwang108** [linkedin/rest.li#36]
Hi, I'm trying to build the Fortune example locally and I'm running into an issue with the gradle script.
When I run "gradle idea", it fails with this error:

No such property: pegasusVersion for class: org.gradle.api.internal.project.DefaultProject_Decorated

Can anyone help? Thanks!

**Comment by ifwonderland** [comment]
Thanks for the question and answer @kwang108  works for me too when using the one in source

**Comment by quanpinjie** [comment]
I meet this error in my project, I want to know how solve this problem.

**Comment by CrendKing** [comment]
Our example project build.gradle is out of date. I'll update.

**Comment by CrendKing** [comment]
Should be fixed in https://github.com/linkedin/rest.li/commit/af237a0b41dfb3e6ba6357319e4752022dd49410
