### ISSUE TITLE
For PDL the namespace for unions clash in python generated code

### ISSUE THREAD

**Issue by fraudies** [linkedin/rest.li#368]
Disclaimer: I fully made up the example and unfortunately it does not make much sense from a design perspective. It's just for illustrative purposes (and rather than using A, B, C...)

Here is the example
----
namespace zoo

record ZooAnimal {
  water: record WaterAnimals {
    animal: union[Dolphin, Whale] // first union
  }
  land: record LandAnimals {
    animal: union[Dog, Camel] // second union
  }
}
---

Here is the problem
For this example the engine will generate only one class zoo.animal.Animal for the second union which clashes with the first class for union.

Currently, there are two ways to solve this
A) rename the animal attribute, e.g. for LandAnimals, e.g. animal -> landAnimal ... feels cumbersome
B) Define LandAnimals and WaterAnimals in separate files and namespaces ... feels constructed

Why did we not include the surrounding record name into the namespace, e.g. generate zoo.wateranimals.animal.Animal and zoo.landanimals.animal.Animal?

**Comment by evanw555** [comment]
This bug isn't relevant to this codebase. I'll reach out to you offline to redirect you to the appropriate forum.
