### ISSUE TITLE
HELP! Can't download linkedin libs

### ISSUE THREAD

**Issue by kwang108** [linkedin/rest.li#37]
When I run gradle build at the top level, I'm getting a bunch of compile errors:

 error: package com.linkedin.data.template does not exist
import com.linkedin.data.template.DynamicRecordMetadata;

I don't think the dependency jars were downloaded. I copied the gradle script from the repo and only changed the java version to 1.7.

**Comment by gokselg** [comment]
Closing due to not getting enough information. Feel free to reopen with the requested information.
