### ISSUE TITLE
Cannot run the example given in the quickstart guide ( Plugin with id 'pegasus' not found.)

### ISSUE THREAD

**Issue by vaibhavthapliyal** [linkedin/rest.li#39]
Hi,
I was trying to setup a Rest server using this framework by following the quickstart guide given here:
https://github.com/linkedin/rest.li/wiki/Quickstart:-A-Tutorial-Introduction-to-Rest.Li

When I tried to generate java versions of the model that can be used by the server by running "gradle build" command I get this error.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/user/example-standalone-app/api/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'api'.
> Plugin with id 'pegasus' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

The build.gradle file's contents are exactly as described in the Quickstart guide.

Any help to resolve this error would be appreciated.
Thanks 
Vaibhav

**Comment by CrendKing** [comment]
Do you have the following code in your build.gradle?

```
buildscript {
  repositories {
    mavenCentral()
    mavenLocal()
  }

  dependencies {
    classpath group: 'com.linkedin.pegasus', name: 'gradle-plugins', version: '2.2.5'
  }
}
```

**Comment by vaibhavthapliyal** [comment]
Sorry for the delayed reponse, but the problem was in my build.gradle files. I copied the build.gradle files from the quickstart folder and used them to build all my client, Api and server projects. This solved my problem.

Thanks 
Vaibhav

**Comment by vishalsri87** [comment]
quickstart  folder ??

**Comment by selvan** [comment]
Have faced same issue, copied build.gradle and settings.gradle from https://github.com/linkedin/rest.li/tree/master/examples/quickstart

@vaibhavthapliyal mentions the same.
