### ISSUE TITLE
Compatibility checks should allow for moving onto or off of TypeRefs

### ISSUE THREAD

**Issue by jplaisted** [linkedin/rest.li#404]
The [CompatibilityChecker](https://github.com/linkedin/rest.li/blob/6ecba36a107ca05ebd3089d84e9a5689d8532390/data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityChecker.java) today is rigid when it comes to TypeRefs. If a field is a TypeRef, it must always be a TypeRef. If a field is not a TypeRef, it can never be a TypeRef.

However, moving to/from a TypeRef is backwards and forwards compatible, the json doesn't change (granted, the generated Java does). There is a legitimate use case here, especially for moving on to TypeRefs.

Consider this model

```
record MyRecord {
  myField: union[string, int, RecordA, RecordB]
}
```

I've got a `union` here that is kind of large. Not great. Also, not reusable! I may want to move to a TypeRef to clarify this model and also make that `union` reusable.

```
record MyRecord {
  myField: MyTypeRef
}

typeref MyTypeRef = union[string, int, RecordA, RecordB]
```

This generates the same JSON. However, the generated Java definition does have breaking changes, but I may be willing to live with that. I also assume the generated Avro is compatible, but I'm not sure.

**Comment by jplaisted** [comment]
Example unit test I used to prove the json is the same:

```
namespace com.linkedin.testing

typeref MyTypeRef = union[string, int]
```
```
namespace com.linkedin.testing

record MyUsesTypeRef {
  field: MyTypeRef
}
```
```
namespace com.linkedin.testing

record MyUsesUnion {
  field: union[string, int]
}
```

```
  private static String toJson(RecordTemplate recordTemplate) {
    byte[] jsonBytes = DataMapUtils.dataTemplateToBytes(recordTemplate, true);
    String json = new String(jsonBytes, StandardCharsets.UTF_8);
    return json;
  }

  @Test
  public void typeRefChange() {
    String value = "value";
    MyTypeRef myTypeRef = new MyTypeRef();
    myTypeRef.setString("value");
    MyUsesTypeRef myUsesTypeRef = new MyUsesTypeRef().setField(myTypeRef);

    MyUsesUnion.Field field = new MyUsesUnion.Field();
    field.setString(value);
    MyUsesUnion myUnion = new MyUsesUnion().setField(field);

    assertThat(toJson(myUsesTypeRef)).isEqualTo(toJson(myUnion));
  }
```

**Comment by karthikbalasub** [comment]
CompatibilityChecker support [CompatibilityOption](https://github.com/linkedin/rest.li/blob/master/data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityOptions.java#L77), which allows it to run in DATA mode to check wire compatibility or SCHEMA mode which includes typerefs. 

The resource compatibility checker is explicitly using the SCHEMA mode to ensure the client bindings are not broken. 

If your usecase is to run the compatibility checker directly, then I suggest you use the DATA model in options. If you want to use it in resource compatibility checker, we'd have to add that as an option (default would be SCHEMA).

**Comment by jplaisted** [comment]
Ah, I missed that somehow, thank you!

I'm using `CompatibilityChecker.checkCompatibility` directly, so this shouldn't be an issue.

I've basically wrapped that method in a gradle plugin to provide backwards compatibility checks without restli. We use this internally at LI for DataHub's models. Ideally it would be part of the Pegasus plugin, but we didn't have time to port it. We had this on our list of asks earlier this week :)

**Comment by karthikbalasub** [comment]
We are working on a compatibility checker for pegasus models. You should be able to use that directly when it is ready.
@nickibi In the new checker, we should add a config to choose DATA/SCHEMA mode for checking.

**Comment by jplaisted** [comment]
Yeah, sounds good. We made that plugin knowing we'd kill it eventually when it moved to pegasus.

My plan is similar right now: edit the plugin extension to accept the mode.

**Comment by nickibi** [comment]
@karthikbalasub I will add config to choose DATA/SCHEMA mode for checking.
