### ISSUE TITLE
@PathKey annotation?

### ISSUE THREAD

**Issue by jpbetz** [linkedin/rest.li#42]
Rest.li currently provides access to the path keys (for parent resources) via the context and via the @PathKeys annotation.

A minor improvement might be to add support for a @PathKey annotation to get a single parent's path key, e.g.:

get(..., @PathKey("parentId") ParentKey parentKey)

The main advantage of this is that the developer can avoid the type cast that is required when using PathKeys or context, and rest.li can statically check that the parent key (e.g. "parentId") in the get params is valid.

**Comment by kentalabur** [comment]
Apologies for the late reply. I have a couple of clarifying questions.

1. Are you suggesting to add a `ParentKey` class that acts as a wrapper to the key you are retrieving from `PathKeys`? If so, I'm supposing you would also need to add a `getAsParentKey(String key)` method in `PathKeys` to use when reading in the annotation in restli.

2. Assuming the above, I'm not sure what the advantage of this is in regards to avoiding type casting. In the end, the user would probably want a `long` or `String` valued key to use in their resource methods, which means the `ParentKey` class would also have to implement `getAsLong()`, `getAsString()`, etc. methods similar to `PathKeys`.

**Comment by jpbetz** [comment]
No, I'm not suggesting a new `ParentKey` class be added to rest.li it's self.  To clarify, I'm suggesting that if the parent's key type is a primitive type, like `string`, that the usage would be like:

`get(..., @PathKey("parentId") String parentKey)`

And if the parent's key is a complex type, say `UserId`, then the usage would be like:

`get(..., @PathKey("parentId") UserId parentKey)`

Compare this to the current API:

````
... get(..., @Keys PathKeys keys) {
  String parentKey = keys.getAsString("parentId");
}
```

In the current API, the `keys.getAsString("parentId")` can fail at runtime with two main types of errors:

- There is no path key named "parentId"
- The parentId is not of type String

If instead, `@PathKey("parentId") String parentKey` were used, rest.li would be able to (and should) statically check that the parentId is valid and that the type of the parameter is of the correct type, meaning that both the checks would be performed at build time rather than run time.

**Comment by kentalabur** [comment]
I see what you mean now, and I agree having this checked at build time on the rest.li side makes more sense. Considering we have to maintain backwards compatibility with the existing `@PathKeys` annotation which gets the `PathKeys` instance, may I suggest that we introduce a new annotation, say `@PathKeysGet` which will implement this new behavior? I am assuming that this annotation covers not just sub resource keys but any key (e.g. association resource keys) in `PathKeys`. We will also have to check our usages and see how we want to prioritize implementing this feature.

**Comment by jpbetz** [comment]
You could just call it `PathKey` (singular) and leave `PathKeys` as is for backward compatibility.  Because `PathKey` will have a single required argument (e.g. `@PathKey("userId") userIdKey` and `PathKeys` won't (it's always just `@PathKeys pathKeys`, they shouldn't be easily confused with one another.

**Comment by kentalabur** [comment]
Sure, let's stick with `PathKey` then.

**Comment by evanw555** [comment]
Closing, as this has been supported for a while now as `PathKeyParam`. Looks like it was added in June 2016.
