### ISSUE TITLE
Support for SSL and OAuth

### ISSUE THREAD

**Issue by vaibhavthapliyal** [linkedin/rest.li#43]
Dear all,
I have built a rest service using rest.li. I want to know how to have a Transport Security Layer(SSL layer) for that service? Is this feature provided in the framework itself?
I also want to know how can I manage OAuth 2.0 with a rest.li service.
I am using Netty implementation of the server.
Thanks 
Vaibhav

**Comment by thebenwaters** [comment]
+1

**Comment by vaibhavthapliyal** [comment]
Is anybody working on this?

**Comment by ssheng** [comment]
Hi @vaibhavthapliyal, sorry for the late response. HttpNettyServer class (I assume this is what you are using) does not yet have support SSL. But adding it should only require minimal work. Below is an example on how to add SSL to a Netty server. I can review the pull request when it's prepared.

https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/helloworld/HttpHelloWorldServerInitializer.java

Alternatively, you can use a servlet container that already supports SSL.

Thanks,
Sean

**Comment by neeraj-pandey** [comment]
+1

**Comment by jjoyce0510** [comment]
Hi folks, it seems as though the provided [HttpNettyServer](https://github.com/linkedin/rest.li/blob/bda98704c4cbfd940a41c5519deee0837124736e/r2-netty/src/main/java/com/linkedin/r2/transport/http/server/HttpNettyServer.java) has been since updated to support SSL. 

Is this characterization correct? If so maybe this thread can be closed out?

**Comment by ssheng** [comment]
@jjoyce0510 that is correct. TLS support has been added to [HttpNettyServer](https://github.com/linkedin/rest.li/blob/bda98704c4cbfd940a41c5519deee0837124736e/r2-netty/src/main/java/com/linkedin/r2/transport/http/server/HttpNettyServer.java). I'm closing this issue. Thanks.
