### ISSUE TITLE
Grammar issue in Wiki & website blurb

### ISSUE THREAD

**Issue by gnb** [linkedin/rest.li#47]
The Wiki and website both show a blurb containing the sentence "Rest.li fills a niche for applying RESTful principals at scale with an end-to-end developer workflow for buildings REST APIs that promotes clean REST practices".  The correct word is "principles" not "principals".

http://www.quickanddirtytips.com/education/grammar/principal-versus-principle

**Comment by gokselg** [comment]
Fixed the wiki.
