### ISSUE TITLE
Changes to pegasus code generation break certain clones

### ISSUE THREAD

**Issue by jplaisted** [linkedin/rest.li#488]
Clones of record templates made using the constructor which accepts a `DataMap` are no longer "views" of the original. i.e. if one of these records updates, the other _used to_ update as well, but no longer does, at least when accessing fields. The underlying map still updates, which can actually lead to the getters / setters getting out of sync with the underlying data map.

```
  @Test
  public void example() {
    CorpUserInfo info = new CorpUserInfo();
    info.setActive(false);

    // Clone via constructor using the same data map
    CorpUserInfo clone = new CorpUserInfo(info.data());

    assertSame(info.data(), clone.data()); // both are using the same map

    assertFalse(clone.isActive()); // first call reads from the map to the field, and basically caches the result

    info.setActive(true); // change the value on the original

    assertTrue(clone.data().getBoolean("active")); // the map updated on the clone
    assertTrue(clone.isActive()); // in the new code this fails as it returns the cached (field) value, which did not
                                  // update
  }
```

The issue is that the new code introduced fields into records which act as caches, rather than just having methods always access the map, *and* the new setter does not fire change notifications on the map, meaning the other instance is never notified of the change. My guess is this lack of change event is well intentioned (avoid having the same instance get notified), but it ends up changing behavior.

```
@Nonnull
public Boolean isActive() {
    if (_activeField!= null) {
        return _activeField;
    } else {
        Object __rawValue = super._map.get("active");
        if (__rawValue == null) {
            throw new RequiredFieldNotPresentException("active");
        }
        _activeField = DataTemplateUtil.coerceBooleanOutput(__rawValue);
        return _activeField;
    }
}

public CorpUserInfo setActive(boolean value) {
    CheckedUtil.putWithoutCheckingOrChangeNotification(super._map, "active", value);
    _activeField = value;
    return this;
}
```

**Comment by karthikbalasub** [comment]
This issue was fixed in pegasus 29.10.1. Can you confirm if you still see the issue in that version?

**Comment by jplaisted** [comment]
Ah, yes, silly me, I forgot to include I was using 29.7.6. Let me try with 29.10.1+.

**Comment by jplaisted** [comment]
Yes, this test example passes now, thanks!
