### ISSUE TITLE
Filtering unrecognized fields in same traversal as validation?

### ISSUE THREAD

**Issue by jpbetz** [linkedin/rest.li#49]
It is trivial to filter unrecognized field (fields that are not identified by the current version of a schema) in Pegasus.  Validation is also straight forward.  But to do both separately requires traversing the data twice.

Would it be reasonable to extend the validatior to filter unrecognized fields as a FIxup?  This was suggested in my last pull request about a similar topic. To be totally honest, treating this as a FIxup seems like a bit of a stretch to me, but I can't think of any particular problems it would cause.  I suppose the only alternative would be do have some way to easily call a validator on individual data elements and then code a custom traversal in application code that does both the validation and filtering.

Is this something the rest.li team would like to take on or would you prefer a pull request?  If you'd like a pull request, please summarize the approach you'd like us to take.

Thanks!

**Comment by kvidhani** [comment]
Hi Joe,

Erluo recently added a filter, which he described earlier, which actually
performs this fixup you mention.

It creates a new DataMap, then recursively walks through the data and
places things that comply only with the schema into the DataMap. He then
constructs a new RecordTemplate using this DataMap. The resulting DataMap
is guaranteed to fields which only comply with the schema.

This does require an additional traversal of the data, but the uses cases
where this will be used the data will be small anyway.

We didn't check it into Pegasus, but we should be able to move it over from
an internal repo into Pegasus.

Would this help you with your use case? Well it should help you atleast for
the filtering use case....

- Karim

**Comment by jpbetz** [comment]
Hi Karim,

Per my original comment, I believe we can already do that easily enough via:

```
Builder.create(data, schema, IterationOrder.PRE_ORDER).filterBy(AbsentSchemaPredicate).remove();
```

Where `AbsentSchemaPredicate` just checks if `element.getSchema == null`.

The question in this issue is specifically if we can/should combine that with validation somehow to get down to a single traversal.

Does that make sense?

**Comment by kvidhani** [comment]
Hi Joe,

Here is what we propose. This should solve our trim problem in a cleaner
way and help you cover your use cases as well.

We will modify the validator to take 3 different enum values, ignore,
disallow and trim.

Ignore will simply ignore, and based on your RB, will remain the default.

Disallow will add a message which fail validation.

Trim will not add a message (therefore not fail validation) and will remove
this element from the data map.

This will accomplish everything we need and do it in one pass.

Now for the trimming portion, it seems that we can't call it.remove() based
on your RB. In such a case we will need to modify the iterator itself as
you suggested using the predicate. We could tack that on when create the
iterator and the predicate itself would check the enum value.

What are your thoughts on this approach?

- Karim

**Comment by jpbetz** [comment]
Sounds great! Do you need me to propose the change or would you like to drive this one?

**Comment by kvidhani** [comment]
Hi Joe,

Can you make the change along with tests and send us the diff? We'll have
to go through our internal workflow (which you probably remember) to commit
here at which point the change will make it to open source.

We can't approve your pull request directly because there is no way for
open source changes to make it into our repository here at LinkedIn.

- Karim

**Comment by jpbetz** [comment]
That's totally fine.  I'll send you the diff in the form of a pull request, and you can download it, review it and apply it however is most convenient.  I'll try to get you something this week.
