### ISSUE TITLE
Schema error for self referencing Typeref

### ISSUE THREAD

**Issue by jpbetz** [linkedin/rest.li#51]
I was using the below schema to test some pegasus functionality.  When I generate Pegasus Java data bindings for it, the schema for the generated `UnionTyperefInfo` class fails during parsing.  This appears to be related to the indirect self reference.

Stack Trace:
```
Caused by: java.lang.IllegalArgumentException: 1,787: "TypedDefinition" or "org.coursera.models.test.TypedDefinition" cannot be resolved.
1,761: {name=typedDefinition, optional=true, type=TypedDefinition} is not a valid field.

	at com.linkedin.data.template.DataTemplateUtil.parseSchema(DataTemplateUtil.java:298)
	at com.linkedin.data.template.DataTemplateUtil.parseSchema(DataTemplateUtil.java:276)
	at org.coursera.models.test.TypedDefinition$UnionTyperefInfo.<clinit>(TypedDefinition.java:121)
	... 37 more
```

Schema:

```
{
  "name": "Complex",
  "namespace": "org.coursera.models.test",
  "type": "record",
  "fields": [
    { "name": "int", "type": "int", "optional": true },
    { "name": "long", "type": "long", "optional": true },
    { "name": "float", "type": "float", "optional": true },
    { "name": "double", "type": "double", "optional": true },
    { "name": "boolean", "type": "boolean", "optional": true },
    { "name": "string", "type": "string", "optional": true },
    {
      "name": "record",
      "type": {
        "name": "Record",
        "namespace": "org.coursera.models.test",
        "type": "record",
        "fields": [
          { "name": "int", "type": "int", "optional": true }
        ]
      },
      "optional": true
    },
    { "name": "union", "type": [ "string", "Complex" ], "optional": true },
    { "name": "map", "type": { "type": "map", "values": "Complex" }, "optional": true },
    { "name": "array", "type": { "type": "array", "items": "Complex" }, "optional": true },
    {
      "name": "typedDefinition", "type": {
        "name": "TypedDefinition",
        "namespace": "org.coursera.models.test",
        "type": "typeref",
        "ref": [ "org.coursera.models.test.Complex", "Record" ],
        "typedDefinition": {
          "org.coursera.models.test.Complex": "complex",
          "Record": "record"
        }
      },
      "optional": true
    },
    {
      "name": "flatTypedDefinition", "type": {
        "name": "FlatTypedDefinition",
        "namespace": "org.coursera.models.test",
        "type": "typeref",
        "ref": [ "Complex", "org.coursera.models.test.Record" ],
        "flatTypedDefinition": {
          "Complex": "complex",
          "org.coursera.models.test.Record": "record"
        }
      },
      "optional": true
    }
  ]
}
```

**Comment by jpbetz** [comment]
There is no urgency on this.  I've just changed the schema I test with.  I figured I would report it since it appears to be a legitimate bug in how schemas are handled.

**Comment by kvidhani** [comment]
So it seems you have a typref pointing to a union of multiple types. In this case one of the types is the outer (top level) type and another type called 'Record'. As you know its acceptable to have a typref referencing a union. 

However in your the problem seems that 'Record' cannot be resolved. Complex is the outer, top level type which you have provided with the full name space. Where is 'Record' coming from? Is this the same 'Record' as you defined inline earlier above?

**Comment by jpbetz** [comment]
The problem is that `TypedDefinition` cannot be resolved.

Yes, 'Record' is declared inline here and then referenced by name later.  This is how SchemaToJsonEncoder serializes denormalized schemas to JSON, and is by the schema parser (or else the entire record template system is would not work properly).

Note that is only occurs when the java record templates are generated and then `UnionTyperefInfo` is initialized.

**Comment by kvidhani** [comment]
Can you try org.coursera.models.test.Record?

**Comment by CrendKing** [comment]
I just gave the latest pegasus a try, and it works. Attached the generated java files.

[test.zip](https://github.com/linkedin/rest.li/files/92643/test.zip)
