### ISSUE TITLE
python & 2.0 encoding of query params

### ISSUE THREAD

**Issue by bitsofinfo** [linkedin/rest.li#527]
Trying to use python for generically url encoding query params that are fed into the client from another system, and quickly ran into the roadblock of being able to use something like `urllib.parse.urlencode(myDictOfKVPairs)` for rest.li endpoints.

https://linkedin.github.io/rest.li/spec/protocol

for example: 
```
myparams = { 
"timeIntervals": "(timeRange:(start:1612185776000,end:1612963376000),timeGranularityType:DAY)"
}

qs = urllib.parse.urlencode(myparams)
```

Yields errors like `{"message":"Parameter 'timeIntervals' is invalid","status":400}` due to the rest.li backend demanding that in this case the parens `()` not be encoded..... 

... did some searching but not finding any py libs that handle this, unless I'm missing something... any py libs or helpers out there for this that you know of or use internally?

**Comment by aman1309** [comment]
@bitsofinfo can you reach out to the python team for any utility they might have for this? Let's discuss offline regarding python since its not open source yet.
