### ISSUE TITLE
Docs inconsistent about @ActionParam usage in @Finder methods

### ISSUE THREAD

**Issue by Valloric** [linkedin/rest.li#56]
In the User Guide:

> @ActionParam is only allowed in Action methods, while @QueryParam is allowed in all non-Action methods.

([source](https://github.com/linkedin/rest.li/wiki/Rest.li-User-Guide#actionparam-vs-queryparam))

Then in the [Finder docs](https://github.com/linkedin/rest.li/wiki/Rest.li-User-Guide#finder):

> Every parameter of a finder method must be annotated with one of:
> [...] @ActionParam [...]

So which is it? Can `@ActionParam` be used in `@Finder` methods or not?

**Comment by CrendKing** [comment]
The user guide doc is correct. The finder doc should be updated.

However, this also involves a code bug fix. I'll update this issue once the fix is pushed.

**Comment by CrendKing** [comment]
Fixed in https://github.com/linkedin/rest.li/commit/9cef4b48ac369a05ef279d8d58acd65059e546ad.
