### ISSUE TITLE
Adding a required field with default is considered non-compatible

### ISSUE THREAD

**Issue by richardchen331** [linkedin/rest.li#57]
Adding a required field with default is considered non-compatible by the [CompatibilityChecker](https://github.com/jpbetz/rest.li/blob/master/data/src/main/java/com/linkedin/data/schema/compatibility/CompatibilityChecker.java). I tried to come up with a case where adding a required field would be unsafe but can’t think of any.

Is this indeed incompatible? If not then the compatibility checker should take defaults into account.

**Comment by CrendKing** [comment]
This is actually a fairly complicated question. We have passionately discussed about this and reached conclusion.

Traditionally when the data layer of Rest.li is firstly designed, the designer considered required/optional is completely orthogonal property to having default value. It is possible to have 4 states:

1. required field without default value
2. required field with default value
3. optional field without default value
4. optional field with default value

The data layer then build other tools around this assumption. Some tools treat states 2 and 4 differently while most other tools treat them the same. Two notable situations are 1) `ValidateDataAgainstSchema` with `RequiredMode` == `MUST_BE_PRESENT`; and 2) pdsc <-> avsc conversions. The cases where they are treated the same are more common, for example, RecordTemplate field access, `ValidateDataAgainstSchema` with other `RequiredMode`, etc.

When the compatibility checker was introduced, we followed the "treat them differently" approach. However, we realized that this approach may not give user the most intuitive experience. Therefore, in the future we may switch to the other approach.

For now, if your use cases do not involve the two situations listed above, you can probably disregard the warning from the compatibility checker. When we are ready to make the switch, we will release new version. Thank you!
