### ISSUE TITLE
The rest.li protocol spec doesn't specify how to encode multibyte characters.

### ISSUE THREAD

**Issue by nathanhammond** [linkedin/rest.li#58]
See: https://github.com/linkedin/rest.li/wiki/Rest.li-Protocol

**Comment by xma000** [comment]
Standard URL encoding applies to string values. (See https://github.com/linkedin/rest.li/wiki/Rest.li-Protocol#definitions) In short, percent-encoding is applied. For non-ASCII characters, UTF-8 encoding is used to get the octets used for percent-encoding. (See https://tools.ietf.org/html/rfc3986#section-2.5)
