### ISSUE TITLE
The rest.li protocol spec doesn't specify how to encode empty strings as key values.

### ISSUE THREAD

**Issue by nathanhammond** [linkedin/rest.li#59]
JSON allows empty strings as key values: `console.log({"": "asdf"}[""]);` What should the behavior be in Rest.li?

**Comment by xma000** [comment]
Empty string is encoded as two single quotes like ''. This is now documented at https://github.com/linkedin/rest.li/wiki/Rest.li-Protocol#empty-string-parameters
