### ISSUE TITLE
Failed to "gradle build" the example project in Windows 10

### ISSUE THREAD

**Issue by HeidernBuffalo** [linkedin/rest.li#63]
OS: Windows 10.
My steps:
1. Check out the whole rest.li repo from github.
2. cd example/quickstart
3. gradle publishRestliIdl   - This step already generated some warnings but succeeded.
4. gradle build - Failure

C:\Users\huang\Documents\GitHub\rest.li\examples\quickstart [master]> gradle build
FAILURE: Build failed with an exception.
* Where:
Build file 'C:\Users\huang\Documents\GitHub\rest.li\examples\quickstart\build.gradle' line: 50
* What went wrong:
A problem occurred configuring project ':api'.
> Cannot change dependencies of configuration ':api:restClientCompile' after it has been resolved.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED

Total time: 2.557 secs

**Comment by CrendKing** [comment]
Our example project build.gradle is out of date. I'll update.

**Comment by CrendKing** [comment]
Check https://github.com/linkedin/rest.li/commit/af237a0b41dfb3e6ba6357319e4752022dd49410
