### ISSUE TITLE
Java 8 is required for build

### ISSUE THREAD

**Issue by xianhengma** [linkedin/rest.li#65]
```
if(!project.sourceCompatibility.isJava8Compatible()) // lower bound of java versions we support.
{
      throw new GradleScriptException("Pegasus required Java 8 or later to build, current version: ${JavaVersion.current()}", null)
}
```
Java 8 is required for build while https://github.com/linkedin/rest.li/wiki#requirements is still showing:
- Java 1.6+

PermGen has been removed from JDK8, so the following parameter in https://github.com/linkedin/rest.li/wiki/Building-Rest.li-from-Source#out-of-memory-while-trying-to-build is also unnecessary:
-XX:MaxPermSize=1024M

**Comment by ssheng** [comment]
Looks like wiki has been updated. Closing issue.
