### ISSUE TITLE
Upgrade Jackson

### ISSUE THREAD

**Issue by benmccann** [linkedin/rest.li#73]
It would be helpful to upgrade Jackson to a newer version. I'm having trouble since rest.li uses an older version than Play (2.7.2) and other libraries do.

I tried updating myself, but I couldn't update past 2.4.6 and get the tests to pass still

**Comment by kvidhani** [comment]
This is a good suggestion. I'll go ahead and try to make this change. I'll update this thread with my status.

**Comment by benmccann** [comment]
@kvidhani any progress on this?

**Comment by benmccann** [comment]
Yeah, I think that'll work for us. I wouldn't mind an upgrade to 2.8.9, but this should let us get rid of our workaround
