### ISSUE TITLE
Deco Framework?

### ISSUE THREAD

**Issue by gzak** [linkedin/rest.li#74]
As a former LI-er, I miss the deco framework :-)

Any plans to release any part of it as open source--perhaps just the spec for the query language itself? I think it would be a major addition to LI's open source suite, as it simplifies a very real problem faced by many in a service oriented architecture containing lots of services.

**Comment by kvidhani** [comment]
Hi there!

We do indeed have plans of open sourcing deco, but at the moment it's not a
in a state where we can do so. Here are the reasons why:

1. Code quality is not ideal. We want pull requests to come in and
subsequently work with developers, but in it's current state it will cause
more confusion then benefit. We need to improve test coverage as well.
2. Deco is tightly coupled with rest.li. We have plans of making it general
purpose so it can fit in with any server to server environment.
3. The spec itself although compact and efficient is a bit cryptic at times
to understand. Furthermore its written only for Java right now. We see more
benefit in investing in open sourcing all of deco itself rather then just
the spec right now.

I will save your email and give you a heads up with this does indeed happen.

Thanks again!

- Karim

**Comment by junchuanwang** [comment]
Closing as the condition no longer apply.
