### ISSUE TITLE
Don't throw exceptions on 2xx response codes

### ISSUE THREAD

**Issue by benmccann** [linkedin/rest.li#90]
RestLi seems to throw an exception if the response code is not 200

All 2xx response codes are supposed to indicate Success. E.g. we're returning 204 when there are 0 results and everything is okay. Rest.li throws an exception in this case which causes issues with out monitoring software

Probably only responses codes `>= 400` should throw an exception, but certainly no 2xx response code should

**Comment by joelhare** [comment]
Can you give an example of why you think Rest.Li is throwing an exception on anything but 200?

**Comment by benmccann** [comment]
@linjer suggested I may have been mistaken and the issue was on our side and not on the rest.li side

**Comment by joelhare** [comment]
Okay, thanks for following up.
