### ISSUE TITLE
LinkedIn webapp in settings 

### ISSUE THREAD

**Issue by featherduino** [linkedin/rest.li#912]
![image](https://github.com/linkedin/rest.li/assets/17808683/5522edaf-3ca4-4560-9295-d2d9d3edaf16)
didn't know where to raise this so raised this here 
UI orientation faulty
please check

**Comment by zackthehuman** [comment]
Thanks for letting us know, @featherduino. Sorry that the UI is not working properly on your device. The best place to report this is on the LinkedIn Help Center (https://www.linkedin.com/help/linkedin/solve). A support agent can route this issue to the correct applications team.
